#!/bin/bash

cat test_d/org.txt > org.txt
cat test_c/basketballdrill/org.txt >> org.txt
cat test_c/bqmall/org.txt >> org.txt
cat test_c/flowervase/org.txt >> org.txt
cat test_c/partyscene/org.txt >> org.txt
cat test_c/racehorses/org.txt >> org.txt
cat test_e/fourpeople/fourpeople_rate1/org.txt >> org.txt
cat test_e/fourpeople/fourpeople_rate2/org.txt >> org.txt
cat test_e/fourpeople/fourpeople_rate3/org.txt >> org.txt
cat test_e/fourpeople/fourpeople_rate4/org.txt >> org.txt
cat test_e/johnny/johnny_rate1/org.txt >> org.txt
cat test_e/johnny/johnny_rate2/org.txt >> org.txt
cat test_e/johnny/johnny_rate3/org.txt >> org.txt
cat test_e/johnny/johnny_rate4/org.txt >> org.txt
cat test_e/kristenandsara/kristenandsara_rate1/org.txt >> org.txt
cat test_e/kristenandsara/kristenandsara_rate2/org.txt >> org.txt
cat test_e/kristenandsara/kristenandsara_rate3/org.txt >> org.txt
cat test_e/kristenandsara/kristenandsara_rate4/org.txt >> org.txt
cat test_e/vidyo1/vidyo1_rate1/org.txt >> org.txt
cat test_e/vidyo1/vidyo1_rate2/org.txt >> org.txt
cat test_e/vidyo1/vidyo1_rate3/org.txt >> org.txt
cat test_e/vidyo1/vidyo1_rate4/org.txt >> org.txt
cat test_e/vidyo3/vidyo3_rate1/org.txt >> org.txt
cat test_e/vidyo3/vidyo3_rate2/org.txt >> org.txt
cat test_e/vidyo3/vidyo3_rate3/org.txt >> org.txt
cat test_e/vidyo3/vidyo3_rate4/org.txt >> org.txt
cat test_e/vidyo4/vidyo4_rate1/org.txt >> org.txt
cat test_e/vidyo4/vidyo4_rate2/org.txt >> org.txt
cat test_e/vidyo4/vidyo4_rate3/org.txt >> org.txt
cat test_e/vidyo4/vidyo4_rate4/org.txt >> org.txt
cat test_e/zaowujie/zaowujie_rate1/org.txt >> org.txt
cat test_e/zaowujie/zaowujie_rate2/org.txt >> org.txt
cat test_e/zaowujie/zaowujie_rate3/org.txt >> org.txt
cat test_e/zaowujie/zaowujie_rate4/org.txt >> org.txt
cat test_b/basketballdrive_rate1/org.txt >> org.txt
cat test_b/basketballdrive_rate2/org.txt >> org.txt
cat test_b/basketballdrive_rate3/org.txt >> org.txt
cat test_b/basketballdrive_rate4/org.txt >> org.txt
cat test_b/bqterrace_rate1/org.txt >> org.txt
cat test_b/bqterrace_rate2/org.txt >> org.txt
cat test_b/bqterrace_rate3/org.txt >> org.txt
cat test_b/bqterrace_rate4/org.txt >> org.txt
cat test_b/cactus_rate1/org.txt >> org.txt
cat test_b/cactus_rate2/org.txt >> org.txt
cat test_b/cactus_rate3/org.txt >> org.txt
cat test_b/cactus_rate4/org.txt >> org.txt
cat test_b/kimono1_rate1/org.txt >> org.txt
cat test_b/kimono1_rate2/org.txt >> org.txt
cat test_b/kimono1_rate3/org.txt >> org.txt
cat test_b/kimono1_rate4/org.txt >> org.txt
cat test_b/parkscene_rate1/org.txt >> org.txt
cat test_b/parkscene_rate2/org.txt >> org.txt
cat test_b/parkscene_rate3/org.txt >> org.txt
cat test_b/parkscene_rate4/org.txt >> org.txt
cat test_f/basketballdrilltext/org.txt >> org.txt
cat test_f/chinaspeed/chinaspeed_rate1/org.txt >> org.txt
cat test_f/chinaspeed/chinaspeed_rate2/org.txt >> org.txt
cat test_f/chinaspeed/chinaspeed_rate3/org.txt >> org.txt
cat test_f/chinaspeed/chinaspeed_rate4/org.txt >> org.txt
cat test_f/slideediting/org.txt >> org.txt
cat test_f/slideshow/slideshow_rate1/org.txt >> org.txt
cat test_f/slideshow/slideshow_rate2/org.txt >> org.txt
cat test_f/slideshow/slideshow_rate3/org.txt >> org.txt
cat test_f/slideshow/slideshow_rate4/org.txt >> org.txt
cat test_a/traffic_rate1/org.txt >> org.txt
cat test_a/traffic_rate2/org.txt >> org.txt
cat test_a/traffic_rate3/org.txt >> org.txt
cat test_a/traffic_rate4/org.txt >> org.txt
cat test_a/peopleonstreet_rate1/org.txt >> org.txt
cat test_a/peopleonstreet_rate2/org.txt >> org.txt
cat test_a/peopleonstreet_rate3/org.txt >> org.txt
cat test_a/peopleonstreet_rate4/org.txt >> org.txt

